export { Hero }        from './Hero'
export { PullQuote }   from './PullQuote'
export { LiveCapture } from './LiveCapture'
export { TryIt }       from './TryIt'
export { WhoItsFor }   from './WhoItsFor'
export { Developer }   from './Developer'
export { Closing }     from './Closing'
export { Footer }      from './Footer'
